device: cuda
batch_size: 128
gradient_accumulation_steps: 1
training:
  max_epochs: 1
  force_epochs: false
  max_steps: 25000
  eval_steps: 100
  save_steps: 500
  use_checkpoint: true
  resume_train: true
  compile_model: true
  train_time_warmup: 1000
logging:
  log_dir: ./models/mytlm-nano/v99.debug/
  interval_steps: 100
checkpoint:
  save_interval_steps: 10000
  keep_latest: true
  backups:
    keep_last: 2
milestones:
  interval_steps: 10000
  dist_subfolder: dist
optimizer:
  name: AdamW
  lr: 0.00015
  weight_decay: 0.1
scheduler:
  type: cosine
  warmup_steps: 2500
model:
  name: mytlm-nano
  vocab_size: 100352
  context_length: 256
  dimension: 256
  hidden_dimension: 804
  n_heads: 8
  num_layers: 64
  non_linearity: gelu
  dropout: 0.1
  tie_weights: true
  use_checkpoint: true
  checkpoint_ratio: 0.5