# ============================================
# DEVICE & GLOBAL SETTINGS
# ============================================
device: cuda
deterministic: false

# ============================================
# TRAINING PARAMETERS
# ============================================
# Optimiser steps 
# max_steps: 9839
max_steps: 9539
# micro-batch size
batch_size: 44

effective_batch_size: 1408 # for my sake only
effective_tokens_per_batch: 2162688 # for my sake only

# ============================================
# TRAINER CONFIG
# ============================================
trainer:
  accum_steps: 32
  max_grad_norm: 1.0
  grad_skip_nan_inf: true
  bf16_autocast: true
  log_grad_norm_every: 0

  val_every_steps: 5     # validate every
  val_max_batches: 50   # no of steps to val on val_dataset
  log_every_steps: 1
  moving_avg_alpha: 0.03

  save_every_steps: 25
  keep_last: 3
  async_ckpt_write: true

  ema_decay: 0.999 # set 0 to turn off
  ema_update_every: 1

  milestone: 100
  resume_train: false
  train_time_warmup: 0
  precomputed_train_time: 144.5007 # precomputed fro bs = 24  ac = 55

# ============================================
# LOGGING & CHECKPOINTS
# ============================================
logging:
  log_dir: ./models/mytlm-base/v0.debug
  interval_steps: 100

# ============================================
# DATASET & DATALOADER
# ============================================
dataset:
  shard_folder_list:
    - ./data/shards/
    - ./data/shards2/
  dynamic_streaming: true

dataloader_settings:
  num_workers: 1
  pin_memory: true
  prefetch_factor: 1
  persistent_workers: true
  val_num_workers: 1
  val_pin_memory: true
  

# ============================================
# OPTIMIZER & SCHEDULER
# ============================================
optimizer:
  name: AdamW
  lr: 0.0002
  betas: [0.9, 0.95]
  eps: 1e-8
  weight_decay: 0.1

scheduler:
  type: cosine
  warmup_steps: 143
  min_lr_percentage: 9.80665 # g

# ============================================
# MODEL
# ============================================
model:
  name: mytlm-base
  vocab_size: 100352
  context_length: 1536
  dimension: 1536
  hidden_dimension: 4224
  n_heads: 256
  n_kv_heads: 128    # 32/8 =  4 members share same KV's
  num_layers: 32
  non_linearity: swiglu
  dropout: 0.1
  tie_weights: true
  use_checkpoint: true
  checkpoint_ratio: 0.5

# ============================================
# GPU & PRECISION
# ============================================
gpu:
  name: AMD
  compile: true
  precision: bf16
  compile_approach: full

# ============================================
# Bench
# ============================================
sweep:
  batch_sizes: [16, 32, 64, 128, 256]
  accum_steps: [1, 4, 8]