device: cuda
precision: bf16
batch_size: 8
gradient_accumulation_steps: 1
max_epochs: 1
logging:
  log_files_dir: ./checkpoints/logs
  train_log_file: ./checkpoints/logs/train.log
  dry_run_log_file: ./checkpoints/logs/dry_run.log
  samples_log_file: ./checkpoints/logs/gen_samples.log
  test_logs_dir: ./checkpoints/logs/tests/
  test_dataset_file: ./checkpoints/logs/tests/test_dataset.log
  test_model_file: ./checkpoints/logs/tests/test_model.log
  test_trainer_file: ./checkpoints/logs/tests/test_trainer.log
  test_utils_file: ./checkpoints/logs/tests/test_utils.log
  interval_steps: 100
  tensorboard_log_dir: ./runs
  wandb:
    project: myt-llm
    entity: myt-llm-entity
checkpoint:
  dir: ./checkpoints/latest
  save_interval_steps: 10000
  keep_latest: true
  backups:
    dir: ./checkpoints/backups
    keep_last: 2
resume:
  enabled: true
  progress_file: ./checkpoints/latest/progress.json
dataset:
  shard_folder: ./data/shards/
  dynamic_streaming: true
dataloader_settings:
  num_workers: 0
  pin_memory: False
optimizer:
  name: AdamW
  lr: 0.0001
  weight_decay: 0.1
training:
  max_steps: 100
  use_checkpoint: true
scheduler:
  type: cosine
  warmup_steps: 1000
milestones:
  dir: ./checkpoints/milestones
  interval_steps: 10000
  dist_subfolder: dist
model:
  name: mytlm-tiny
  vocab_size: 100352
  context_length: 128
  dimension: 128
  n_heads: 8
  num_layers: 12
  hidden_dimension: 512
  non_linearity: gelu
  dropout: 0.1
  tie_weights: true